name: eds_final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  firebase_core: ^2.14.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true

